export const images = {
  angularjs: require("./images/angularjs.jpg"),
  csharp: require("./images/csharp.png"),
  dockerIcon: require("./images/docker-icon.png"),
  git: require("./images/git.jpg"),
  icon: require("./images/icon.png"),
  java: require("./images/java.png"),
  javaScriptLogo: require("./images/JavaScript-logo.png"),
  jeikinsSvg: require("./images/jeikins.svg.png"),
  kubernetSvg: require("./images/kubernet.svg.png"),
  nextjs: require("./images/nextjs.jpg"),
  pythonV2: require("./images/python--v2.png"),
  react: require("./images/react.png"),
  reactNative: require("./images/react-native.png"),
  rubyProgrammingLanguage: require("./images/ruby-programming-language.jpg"),
  svelteLogoByGengns: require("./images/svelte-logo-by-gengns.png"),
  ts: require("./images/ts.png"),
  vueIcon130791: require("./images/vue_icon_130791.png"),
  logo: require("./images/logo.png"),
};
